# -*- coding: utf-8 -*-
"""final_project.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a3oCx_SlgLDLGZHN4u8n9y9apiIJcM23
"""

# Dependencies
import numpy as np
import pandas as pd
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
import datetime as dt

engine = create_engine("sqlite:///avacado.sqlite")

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

# Create our session (link) from Python to the DB
session = Session(engine)

# 1. Import the sqlalchemy extract function.
from sqlalchemy import extract

import matplotlib.pyplot as plt
import pandas as pd
## Read in the dataset from wherever it is located
data = "mock_data_avacado_project.csv"
df = pd.read_csv(data)
df.head()
# Format the independent variable in the model
X = df['type'].values.reshape(-1, 1)
# Print the shape
print(X.shape)
# return a label
X[:10]